### ISSUE TITLE
Requirements tensorflow

### ISSUE THREAD

**Issue by GoubetClem** [FraunhoferIEE/CurriculumAgent#2]
curriculumagent depends on tensorflow ==2.7.0
Is this requirement of version 2.7.0 still relevant ? Dependabot on GitHub advises to bump to more recent versions for security reasons.

**Comment by ML-IEE** [comment]
We updated tensorflow to 2.12. This version is set for the current L2RPN challenge

**Comment by ML-IEE** [comment]
The Package was updated to v1.0.1 and now includes the newer Ray and Tensorflow versions. Therefore, I am going to close this issue now
